-- Schema-drift reconciliation, Stage 4: capture the snapshots / archive subsystem.
-- Plan: docs/superpowers/plans/2026-06-01-schema-drift-reconciliation.md (prod = target).
--
-- The reference-snapshot/restore tooling and the archive schema (archived happy_hour_places
-- data + an org_members compatibility view) were built on prod (dashboard) and never
-- committed. This captures prod's exact definitions so a fresh replay reproduces them.
--
-- IDEMPOTENT / no-op on prod: schema/tables IF NOT EXISTS, indexes IF NOT EXISTS, view +
-- functions + triggers CREATE OR REPLACE, policies drop-then-create, grants idempotent.
--
-- SECURITY NOTE: capture_reference_snapshot + restore_venue_from_snapshot are SECURITY
-- DEFINER and (per prod) granted to anon/authenticated — same exposure class as
-- merge_staging_venues. Captured faithfully here (no-op); hardened in the next migration.

create schema if not exists archive;

-- ── archive.happy_hour_places (archived pre-redesign data) ───────────────────────
create table if not exists archive.happy_hour_places (
  id               bigint generated by default as identity,
  name             text not null,
  address          text,
  neighborhood     text,
  phone            text,
  distance_miles   double precision,
  cuisine_type     text,
  happy_days       text[] not null default '{}'::text[],
  start_time       time without time zone,
  end_time         time without time zone,
  deal_description text,
  average_price    numeric(10,2),
  status           text not null default 'verified',
  last_confirmed_at timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  business_url     text,
  website_url      text,
  opening_hours    text,
  rating           numeric,
  org_name         text,
  venue_name       text,
  org_slug         text,
  venue_city       text,
  venue_state      text,
  venue_zip        bigint,
  constraint happy_hour_places_pkey primary key (id),
  constraint happy_hour_places_status_check check (status = any (array['draft','pending_review','verified','paused','expired']))
);
create index if not exists happy_hour_places_days_gin     on archive.happy_hour_places using gin (happy_days);
create index if not exists happy_hour_places_org_slug_idx  on archive.happy_hour_places using btree (org_slug);
create index if not exists happy_hour_places_status_idx    on archive.happy_hour_places using btree (status);
alter table archive.happy_hour_places enable row level security;
drop policy if exists happy_hour_places_select_public_verified on archive.happy_hour_places;
create policy happy_hour_places_select_public_verified on archive.happy_hour_places
  for select using (status = 'verified');
grant all on table archive.happy_hour_places to anon, authenticated, service_role;

create or replace trigger happy_hour_places_set_updated_at before update on archive.happy_hour_places
  for each row execute function public.set_updated_at();
create or replace trigger trg_set_updated_at before update on archive.happy_hour_places
  for each row execute function public.set_updated_at();

-- ── archive.organization_members (compat view over public.org_members) ────────────
create or replace view archive.organization_members with (security_invoker = on) as
  select org_id as organization_id, user_id, role, created_at from public.org_members;
grant all on table archive.organization_members to anon, authenticated, service_role;

-- ── public snapshot tables (RLS-enabled, no policy → service_role/owner only) ─────
create table if not exists public.reference_snapshots (
  id         uuid not null default gen_random_uuid(),
  label      text not null,
  notes      text,
  created_by uuid,
  created_at timestamptz not null default now(),
  row_counts jsonb not null default '{}'::jsonb,
  constraint reference_snapshots_pkey primary key (id),
  constraint reference_snapshots_created_by_fkey foreign key (created_by) references auth.users (id)
);
alter table public.reference_snapshots enable row level security;
grant all on table public.reference_snapshots to anon, authenticated, service_role;

create table if not exists public.venues_snapshot (
  snapshot_id uuid not null,
  venue_id    uuid not null,
  data        jsonb not null,
  captured_at timestamptz not null default now(),
  constraint venues_snapshot_pkey primary key (snapshot_id, venue_id),
  constraint venues_snapshot_snapshot_id_fkey foreign key (snapshot_id) references public.reference_snapshots (id) on delete cascade
);
alter table public.venues_snapshot enable row level security;
grant all on table public.venues_snapshot to anon, authenticated, service_role;

create table if not exists public.happy_hour_windows_snapshot (
  snapshot_id uuid not null,
  window_id   uuid not null,
  data        jsonb not null,
  captured_at timestamptz not null default now(),
  constraint happy_hour_windows_snapshot_pkey primary key (snapshot_id, window_id),
  constraint happy_hour_windows_snapshot_snapshot_id_fkey foreign key (snapshot_id) references public.reference_snapshots (id) on delete cascade
);
alter table public.happy_hour_windows_snapshot enable row level security;
grant all on table public.happy_hour_windows_snapshot to anon, authenticated, service_role;

-- ── functions (bodies verbatim from prod) ─────────────────────────────────────────
create or replace function public.capture_reference_snapshot(p_label text, p_notes text default null::text)
  returns uuid language plpgsql security definer as $$
DECLARE
  v_snapshot_id UUID;
  v_venue_count INT;
  v_window_count INT;
BEGIN
  INSERT INTO public.reference_snapshots(label, notes, created_by)
    VALUES (p_label, p_notes, auth.uid())
    RETURNING id INTO v_snapshot_id;

  INSERT INTO public.venues_snapshot(snapshot_id, venue_id, data)
    SELECT v_snapshot_id, v.id, to_jsonb(v.*)
    FROM public.venues v;
  GET DIAGNOSTICS v_venue_count = ROW_COUNT;

  INSERT INTO public.happy_hour_windows_snapshot(snapshot_id, window_id, data)
    SELECT v_snapshot_id, w.id, to_jsonb(w.*)
    FROM public.happy_hour_windows w;
  GET DIAGNOSTICS v_window_count = ROW_COUNT;

  UPDATE public.reference_snapshots
    SET row_counts = jsonb_build_object(
      'venues', v_venue_count,
      'happy_hour_windows', v_window_count
    )
    WHERE id = v_snapshot_id;

  RETURN v_snapshot_id;
END
$$;
grant all on function public.capture_reference_snapshot(text, text) to anon, authenticated, service_role;

create or replace function public.restore_venue_from_snapshot(p_snapshot_id uuid, p_venue_id uuid)
  returns boolean language plpgsql security definer as $$
DECLARE
  v_data JSONB;
BEGIN
  SELECT data INTO v_data
  FROM public.venues_snapshot
  WHERE snapshot_id = p_snapshot_id AND venue_id = p_venue_id;

  IF v_data IS NULL THEN
    RETURN FALSE;
  END IF;

  UPDATE public.venues SET
    name         = v_data->>'name',
    address      = v_data->>'address',
    phone        = v_data->>'phone',
    website      = v_data->>'website',
    neighborhood = v_data->>'neighborhood',
    cuisine_type = v_data->>'cuisine_type',
    city         = v_data->>'city',
    state        = v_data->>'state',
    zip          = v_data->>'zip',
    updated_at   = NOW()
  WHERE id = p_venue_id;

  RETURN TRUE;
END
$$;
grant all on function public.restore_venue_from_snapshot(uuid, uuid) to anon, authenticated, service_role;
